In [6]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
#load data into pandas dataframe..
df = pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx",sheet_name="Transactions")
df.head(5)

,transaction_id,product_id,customer_id,transaction_date,online_order,order_status,brand,product_line,product_class,product_size,list_price,standard_cost,product_first_sold_date
0,1,2,2950,2017-02-25,0.0,Approved,Solex,Standard,medium,medium,71.49,53.62,2012-12-02
1,2,3,3120,2017-05-21,1.0,Approved,Trek Bicycles,Standard,medium,large,2091.47,388.92,2014-03-03
2,3,37,402,2017-10-16,0.0,Approved,OHM Cycles,Standard,low,medium,1793.43,248.82,1999-07-20
3,4,88,3135,2017-08-31,0.0,Approved,Norco Bicycles,Standard,medium,medium,1198.46,381.10,1998-12-16
4,5,78,787,2017-10-01,1.0,Approved,Giant Bicycles,Standard,medium,large,1765.30,709.48,2015-08-10

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19803 entries, 0 to 19802
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   transaction_id           19803 non-null  int64
 1   product_id               19803 non-null  int64
 2   customer_id              19803 non-null  int64
 3   transaction_date         19803 non-null  datetime64[ns]
 4   online_order             19445 non-null  float64
 5   order_status             19803 non-null  object
 6   brand                    19803 non-null  object
 7   product_line             19803 non-null  object
 8   product_class            19803 non-null  object
 9   product_size             19803 non-null  object
 10  list_price               19803 non-null  float64
 11  standard_cost            19803 non-null  float64
 12  product_first_sold_date  19803 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(3), int64(3), object(5)
memory usage: 2.0+ MB

In [4]:
#summary statistics
df.describe()

,transaction_id,product_id,customer_id,online_order,list_price,standard_cost
count,19803.000000,19803.000000,19803.000000,19445.000000,19803.000000,19803.000000
mean,9993.979650,45.815937,1739.294955,0.500849,1107.997866,556.046951
std,5776.499961,30.569841,1011.946353,0.500012,582.770460,405.955660
min,1.000000,0.000000,1.000000,0.000000,12.010000,7.210000
25%,4988.500000,18.000000,858.000000,0.000000,575.270000,215.140000
50%,9995.000000,45.000000,1738.000000,1.000000,1163.890000,507.580000
75%,15000.500000,72.000000,2615.000000,1.000000,1635.300000,795.100000
max,20000.000000,100.000000,5034.000000,1.000000,2091.470000,1759.850000

In [5]:
#checking any null values exist data frame
df.isnull().sum()

transaction_id               0
product_id                   0
customer_id                  0
transaction_date             0
online_order               358
order_status                 0
brand                        0
product_line                 0
product_class                0
product_size                 0
list_price                   0
standard_cost                0
product_first_sold_date      0
dtype: int64

In [7]:
# Looking at all the unique values in features

for i in df.columns:
    print("Unique values in",'',i)
    unique_vals = df[i].unique()
    print(unique_vals)
    print(50*'*')

Unique values in  transaction_id
[    1     2     3 ... 19998 19999 20000]
**************************************************
Unique values in  product_id
[  2   3  37  88  78  25  22  15  67  12   5  61  35  16  79  33  54  27
  82  89  64  19  72  91   1  99   0  92  14  44  76  46  55  66  81  86
  32  77  96   6  47  94  93  60  28   4  38  56  58  50  80  87  84  21
  31  62  17  73  45  49  95  18  70  26  39  36  98  75  42  20  24  53
  65  29  11  10   7  41   9  69  90  97 100  74  71  34  57  23  51  59
  63  40   8  13  30  48  68  83  43  52  85]
**************************************************
Unique values in  customer_id
[2950 3120  402 ... 2764 3168 3464]
**************************************************
Unique values in  transaction_date
['2017-02-25T00:00:00.000000000' '2017-05-21T00:00:00.000000000'
 '2017-10-16T00:00:00.000000000' '2017-08-31T00:00:00.000000000'
 '2017-10-01T00:00:00.000000000' '2017-03-08T00:00:00.000000000'
 '2017-04-21T00:00:00.000000000' '2017-07-15T00:00:00.000000000'
 '2017-08-10T00:00:00.000000000' '2017-08-30T00:00:00.000000000'
 '2017-01-17T00:00:00.000000000' '2017-01-05T00:00:00.000000000'
 '2017-02-26T00:00:00.000000000' '2017-09-10T00:00:00.000000000'
 '2017-06-11T00:00:00.000000000' '2017-10-10T00:00:00.000000000'
 '2017-04-03T00:00:00.000000000' '2017-06-02T00:00:00.000000000'
 '2017-04-06T00:00:00.000000000' '2017-01-28T00:00:00.000000000'
 '2017-10-09T00:00:00.000000000' '2017-06-29T00:00:00.000000000'
 '2017-04-08T00:00:00.000000000' '2017-10-18T00:00:00.000000000'
 '2017-01-10T00:00:00.000000000' '2017-04-11T00:00:00.000000000'
 '2017-12-23T00:00:00.000000000' '2017-10-13T00:00:00.000000000'
 '2017-03-15T00:00:00.000000000' '2017-09-05T00:00:00.000000000'
 '2017-02-18T00:00:00.000000000' '2017-03-20T00:00:00.000000000'
 '2017-02-28T00:00:00.000000000' '2017-08-20T00:00:00.000000000'
 '2017-07-07T00:00:00.000000000' '2017-01-09T00:00:00.000000000'
 '2017-12-06T00:00:00.000000000' '2017-09-12T00:00:00.000000000'
 '2017-11-28T00:00:00.000000000' '2017-05-08T00:00:00.000000000'
 '2017-05-14T00:00:00.000000000' '2017-03-17T00:00:00.000000000'
 '2017-12-22T00:00:00.000000000' '2017-06-07T00:00:00.000000000'
 '2017-06-20T00:00:00.000000000' '2017-05-07T00:00:00.000000000'
 '2017-06-10T00:00:00.000000000' '2017-06-17T00:00:00.000000000'
 '2017-05-10T00:00:00.000000000' '2017-03-24T00:00:00.000000000'
 '2017-11-27T00:00:00.000000000' '2017-12-21T00:00:00.000000000'
 '2017-02-09T00:00:00.000000000' '2017-09-18T00:00:00.000000000'
 '2017-11-14T00:00:00.000000000' '2017-02-15T00:00:00.000000000'
 '2017-12-18T00:00:00.000000000' '2017-02-24T00:00:00.000000000'
 '2017-12-17T00:00:00.000000000' '2017-07-08T00:00:00.000000000'
 '2017-05-16T00:00:00.000000000' '2017-02-23T00:00:00.000000000'
 '2017-07-03T00:00:00.000000000' '2017-09-30T00:00:00.000000000'
 '2017-10-21T00:00:00.000000000' '2017-05-06T00:00:00.000000000'
 '2017-01-03T00:00:00.000000000' '2017-05-09T00:00:00.000000000'
 '2017-07-23T00:00:00.000000000' '2017-01-21T00:00:00.000000000'
 '2017-03-10T00:00:00.000000000' '2017-11-07T00:00:00.000000000'
 '2017-12-16T00:00:00.000000000' '2017-10-07T00:00:00.000000000'
 '2017-04-27T00:00:00.000000000' '2017-04-01T00:00:00.000000000'
 '2017-11-02T00:00:00.000000000' '2017-02-13T00:00:00.000000000'
 '2017-07-19T00:00:00.000000000' '2017-05-23T00:00:00.000000000'
 '2017-08-06T00:00:00.000000000' '2017-04-04T00:00:00.000000000'
 '2017-08-15T00:00:00.000000000' '2017-04-15T00:00:00.000000000'
 '2017-07-25T00:00:00.000000000' '2017-02-21T00:00:00.000000000'
 '2017-05-31T00:00:00.000000000' '2017-06-23T00:00:00.000000000'
 '2017-03-26T00:00:00.000000000' '2017-07-31T00:00:00.000000000'
 '2017-07-27T00:00:00.000000000' '2017-04-14T00:00:00.000000000'
 '2017-11-12T00:00:00.000000000' '2017-10-26T00:00:00.000000000'
 '2017-10-11T00:00:00.000000000' '2017-03-27T00:00:00.000000000'
 '2017-11-04T00:00:00.000000000' '2017-10-24T00:00:00.000000000'
 '2017-05-01T00:00:00.000000000' '2017-11-21T00:00:00.000000000'
 '2017-03-21T00:00:00.000000000' '2017-02-20T00:00:00.000000000'
 '2017-06-16T00:00:00.000000000' '2017-12-04T00:00:00.000000000'
 '2017-12-01T00:00:00.000000000' '2017-03-05T00:00:00.000000000'
 '2017-03-16T00:00:00.000000000' '2017-06-05T00:00:00.000000000'
 '2017-09-04T00:00:00.000000000' '2017-01-18T00:00:00.000000000'
 '2017-09-28T00:00:00.000000000' '2017-09-02T00:00:00.000000000'
 '2017-10-17T00:00:00.000000000' '2017-04-25T00:00:00.000000000'
 '2017-08-02T00:00:00.000000000' '2017-03-25T00:00:00.000000000'
 '2017-01-01T00:00:00.000000000' '2017-12-25T00:00:00.000000000'
 '2017-01-26T00:00:00.000000000' '2017-12-20T00:00:00.000000000'
 '2017-01-13T00:00:00.000000000' '2017-11-11T00:00:00.000000000'
 '2017-08-19T00:00:00.000000000' '2017-08-22T00:00:00.000000000'
 '2017-09-15T00:00:00.000000000' '2017-03-01T00:00:00.000000000'
 '2017-08-16T00:00:00.000000000' '2017-07-10T00:00:00.000000000'
 '2017-12-11T00:00:00.000000000' '2017-05-20T00:00:00.000000000'
 '2017-07-30T00:00:00.000000000' '2017-10-25T00:00:00.000000000'
 '2017-04-26T00:00:00.000000000' '2017-02-02T00:00:00.000000000'
 '2017-05-02T00:00:00.000000000' '2017-10-22T00:00:00.000000000'
 '2017-11-16T00:00:00.000000000' '2017-03-30T00:00:00.000000000'
 '2017-04-13T00:00:00.000000000' '2017-01-31T00:00:00.000000000'
 '2017-03-18T00:00:00.000000000' '2017-01-07T00:00:00.000000000'
 '2017-07-05T00:00:00.000000000' '2017-11-19T00:00:00.000000000'
 '2017-11-08T00:00:00.000000000' '2017-07-24T00:00:00.000000000'
 '2017-01-15T00:00:00.000000000' '2017-01-12T00:00:00.000000000'
 '2017-06-30T00:00:00.000000000' '2017-06-22T00:00:00.000000000'
 '2017-12-27T00:00:00.000000000' '2017-06-08T00:00:00.000000000'
 '2017-07-29T00:00:00.000000000' '2017-05-27T00:00:00.000000000'
 '2017-05-05T00:00:00.000000000' '2017-09-09T00:00:00.000000000'
 '2017-09-22T00:00:00.000000000' '2017-04-12T00:00:00.000000000'
 '2017-12-14T00:00:00.000000000' '2017-03-22T00:00:00.000000000'
 '2017-11-29T00:00:00.000000000' '2017-06-09T00:00:00.000000000'
 '2017-11-13T00:00:00.000000000' '2017-04-09T00:00:00.000000000'
 '2017-11-30T00:00:00.000000000' '2017-03-13T00:00:00.000000000'
 '2017-08-12T00:00:00.000000000' '2017-08-04T00:00:00.000000000'
 '2017-09-01T00:00:00.000000000' '2017-07-02T00:00:00.000000000'
 '2017-03-11T00:00:00.000000000' '2017-10-08T00:00:00.000000000'
 '2017-11-23T00:00:00.000000000' '2017-01-22T00:00:00.000000000'
 '2017-01-29T00:00:00.000000000' '2017-07-21T00:00:00.000000000'
 '2017-02-10T00:00:00.000000000' '2017-11-25T00:00:00.000000000'
 '2017-12-03T00:00:00.000000000' '2017-12-30T00:00:00.000000000'
 '2017-07-26T00:00:00.000000000' '2017-06-15T00:00:00.000000000'
 '2017-07-06T00:00:00.000000000' '2017-12-28T00:00:00.000000000'
 '2017-01-30T00:00:00.000000000' '2017-06-26T00:00:00.000000000'
 '2017-08-13T00:00:00.000000000' '2017-08-27T00:00:00.000000000'
 '2017-01-25T00:00:00.000000000' '2017-07-11T00:00:00.000000000'
 '2017-04-30T00:00:00.000000000' '2017-05-19T00:00:00.000000000'
 '2017-05-26T00:00:00.000000000' '2017-02-03T00:00:00.000000000'
 '2017-04-28T00:00:00.000000000' '2017-03-23T00:00:00.000000000'
 '2017-06-03T00:00:00.000000000' '2017-05-04T00:00:00.000000000'
 '2017-03-29T00:00:00.000000000' '2017-10-03T00:00:00.000000000'
 '2017-08-07T00:00:00.000000000' '2017-02-07T00:00:00.000000000'
 '2017-11-20T00:00:00.000000000' '2017-04-05T00:00:00.000000000'
 '2017-10-28T00:00:00.000000000' '2017-08-25T00:00:00.000000000'
 '2017-01-20T00:00:00.000000000' '2017-03-14T00:00:00.000000000'
 '2017-05-24T00:00:00.000000000' '2017-11-18T00:00:00.000000000'
 '2017-04-07T00:00:00.000000000' '2017-01-04T00:00:00.000000000'
 '2017-12-13T00:00:00.000000000' '2017-04-20T00:00:00.000000000'
 '2017-03-07T00:00:00.000000000' '2017-08-01T00:00:00.000000000'
 '2017-06-19T00:00:00.000000000' '2017-01-23T00:00:00.000000000'
 '2017-04-19T00:00:00.000000000' '2017-08-11T00:00:00.000000000'
 '2017-11-15T00:00:00.000000000' '2017-11-01T00:00:00.000000000'
 '2017-10-05T00:00:00.000000000' '2017-10-30T00:00:00.000000000'
 '2017-01-02T00:00:00.000000000' '2017-07-09T00:00:00.000000000'
 '2017-10-20T00:00:00.000000000' '2017-11-10T00:00:00.000000000'
 '2017-08-14T00:00:00.000000000' '2017-09-13T00:00:00.000000000'
 '2017-05-03T00:00:00.000000000' '2017-01-24T00:00:00.000000000'
 '2017-08-03T00:00:00.000000000' '2017-08-28T00:00:00.000000000'
 '2017-06-24T00:00:00.000000000' '2017-10-27T00:00:00.000000000'
 '2017-03-03T00:00:00.000000000' '2017-12-02T00:00:00.000000000'
 '2017-10-15T00:00:00.000000000' '2017-10-12T00:00:00.000000000'
 '2017-03-19T00:00:00.000000000' '2017-06-27T00:00:00.000000000'
 '2017-02-27T00:00:00.000000000' '2017-03-12T00:00:00.000000000'
 '2017-06-14T00:00:00.000000000' '2017-02-17T00:00:00.000000000'
 '2017-09-14T00:00:00.000000000' '2017-04-17T00:00:00.000000000'
 '2017-05-11T00:00:00.000000000' '2017-11-03T00:00:00.000000000'
 '2017-10-02T00:00:00.000000000' '2017-12-10T00:00:00.000000000'
 '2017-05-25T00:00:00.000000000' '2017-08-26T00:00:00.000000000'
 '2017-09-06T00:00:00.000000000' '2017-04-24T00:00:00.000000000'
 '2017-12-15T00:00:00.000000000' '2017-02-12T00:00:00.000000000'
 '2017-07-22T00:00:00.000000000' '2017-09-26T00:00:00.000000000'
 '2017-12-05T00:00:00.000000000' '2017-03-31T00:00:00.000000000'
 '2017-11-22T00:00:00.000000000' '2017-04-29T00:00:00.000000000'
 '2017-07-14T00:00:00.000000000' '2017-09-08T00:00:00.000000000'
 '2017-04-22T00:00:00.000000000' '2017-01-11T00:00:00.000000000'
 '2017-08-09T00:00:00.000000000' '2017-05-29T00:00:00.000000000'
 '2017-06-13T00:00:00.000000000' '2017-07-28T00:00:00.000000000'
 '2017-04-23T00:00:00.000000000' '2017-07-04T00:00:00.000000000'
 '2017-10-19T00:00:00.000000000' '2017-09-21T00:00:00.000000000'
 '2017-04-02T00:00:00.000000000' '2017-08-18T00:00:00.000000000'
 '2017-08-21T00:00:00.000000000' '2017-03-06T00:00:00.000000000'
 '2017-01-16T00:00:00.000000000' '2017-02-22T00:00:00.000000000'
 '2017-09-23T00:00:00.000000000' '2017-03-09T00:00:00.000000000'
 '2017-01-27T00:00:00.000000000' '2017-12-19T00:00:00.000000000'
 '2017-04-16T00:00:00.000000000' '2017-10-04T00:00:00.000000000'
 '2017-02-16T00:00:00.000000000' '2017-08-17T00:00:00.000000000'
 '2017-02-01T00:00:00.000000000' '2017-12-08T00:00:00.000000000'
 '2017-08-23T00:00:00.000000000' '2017-05-12T00:00:00.000000000'
 '2017-03-04T00:00:00.000000000' '2017-05-28T00:00:00.000000000'
 '2017-07-20T00:00:00.000000000' '2017-07-13T00:00:00.000000000'
 '2017-10-14T00:00:00.000000000' '2017-06-12T00:00:00.000000000'
 '2017-02-14T00:00:00.000000000' '2017-02-11T00:00:00.000000000'
 '2017-10-23T00:00:00.000000000' '2017-06-28T00:00:00.000000000'
 '2017-06-04T00:00:00.000000000' '2017-04-18T00:00:00.000000000'
 '2017-09-16T00:00:00.000000000' '2017-05-15T00:00:00.000000000'
 '2017-05-22T00:00:00.000000000' '2017-06-06T00:00:00.000000000'
 '2017-12-09T00:00:00.000000000' '2017-07-18T00:00:00.000000000'
 '2017-02-06T00:00:00.000000000' '2017-11-09T00:00:00.000000000'
 '2017-06-21T00:00:00.000000000' '2017-07-17T00:00:00.000000000'
 '2017-10-29T00:00:00.000000000' '2017-05-13T00:00:00.000000000'
 '2017-10-06T00:00:00.000000000' '2017-02-04T00:00:00.000000000'
 '2017-11-05T00:00:00.000000000' '2017-02-08T00:00:00.000000000'
 '2017-11-06T00:00:00.000000000' '2017-09-20T00:00:00.000000000'
 '2017-04-10T00:00:00.000000000' '2017-11-17T00:00:00.000000000'
 '2017-12-07T00:00:00.000000000' '2017-12-12T00:00:00.000000000'
 '2017-01-19T00:00:00.000000000' '2017-05-17T00:00:00.000000000'
 '2017-02-19T00:00:00.000000000' '2017-09-19T00:00:00.000000000'
 '2017-09-29T00:00:00.000000000' '2017-05-18T00:00:00.000000000'
 '2017-07-01T00:00:00.000000000' '2017-12-29T00:00:00.000000000'
 '2017-11-24T00:00:00.000000000' '2017-01-08T00:00:00.000000000'
 '2017-08-24T00:00:00.000000000' '2017-07-12T00:00:00.000000000'
 '2017-08-08T00:00:00.000000000' '2017-02-05T00:00:00.000000000'
 '2017-07-16T00:00:00.000000000' '2017-09-27T00:00:00.000000000'
 '2017-01-14T00:00:00.000000000' '2017-03-28T00:00:00.000000000'
 '2017-08-29T00:00:00.000000000' '2017-09-24T00:00:00.000000000'
 '2017-10-31T00:00:00.000000000' '2017-12-24T00:00:00.000000000'
 '2017-09-03T00:00:00.000000000' '2017-09-17T00:00:00.000000000'
 '2017-08-05T00:00:00.000000000' '2017-06-18T00:00:00.000000000'
 '2017-09-07T00:00:00.000000000' '2017-09-25T00:00:00.000000000'
 '2017-06-01T00:00:00.000000000' '2017-11-26T00:00:00.000000000'
 '2017-09-11T00:00:00.000000000' '2017-01-06T00:00:00.000000000'
 '2017-12-26T00:00:00.000000000' '2017-03-02T00:00:00.000000000'
 '2017-05-30T00:00:00.000000000' '2017-06-25T00:00:00.000000000']
**************************************************
Unique values in  online_order
[ 0.  1. nan]
**************************************************
Unique values in  order_status
['Approved' 'Cancelled']
**************************************************
Unique values in  brand
['Solex' 'Trek Bicycles' 'OHM Cycles' 'Norco Bicycles' 'Giant Bicycles'
 'WeareA2B']
**************************************************
Unique values in  product_line
['Standard' 'Road' 'Mountain' 'Touring']
**************************************************
Unique values in  product_class
['medium' 'low' 'high']
**************************************************
Unique values in  product_size
['medium' 'large' 'small']
**************************************************
Unique values in  list_price
[  71.49 2091.47 1793.43 1198.46 1765.3  1538.99   60.34 1292.84 1071.23
 1231.15  574.64   71.16 1057.51 1661.92 1555.58 1311.44  499.53 1362.99
 1469.44  360.4   642.31 1403.5  1720.7   544.05 1415.01 1842.92 1769.64
 2083.94 1289.85 1894.19 1163.89 1151.96  235.63  642.7  1240.31 1635.3
  227.88  363.01  100.35 1458.17 1977.36   12.01 1216.14 1129.13  183.86
  912.52  175.89 1073.07 1179.    958.74  792.9   290.62  752.64  478.16
 1024.66 1945.43  441.49  533.51  569.56 1148.64  495.72 1992.93 1812.75
  945.04  358.39 1873.97 1810.   1775.81 1777.8   795.34  575.27 1172.78
 1065.03 1807.45 1274.93 1890.39  980.37  416.98 1386.84  742.54  230.91
  688.63  748.17 1466.68  202.62 1036.59 1228.07  774.53  586.45 1762.96
 2005.66 1483.2   590.26 1703.52 1577.53 1636.9  1280.28 1061.56  543.39
 1227.34]
**************************************************
Unique values in  standard_cost
[  53.62       388.92       248.82       381.1        709.48
  829.65        45.26        13.44       380.74       161.6
  459.71        56.93       154.4       1479.11       818.01
 1167.18       388.72        57.74       596.55       270.3
  513.85       954.82      1531.42       376.84      1259.36
 1105.75       108.76       675.03        74.51       598.76
  589.27       649.49       125.07       211.37       795.1
  993.66       136.73       290.41        75.26       874.9
 1759.85         7.21      1082.36       677.48       137.9
  141.4        131.92       933.84       707.4        748.9
  594.68       215.14       205.36       298.72       614.8
  333.18        84.99       400.13       528.43       689.18
  297.43       762.63       582.48       507.58       215.03
  863.95      1610.9       1580.47       820.78       101.58
  431.45      1043.77       230.09       778.69       764.96
  260.14       234.43       312.74      1234.29       667.4
  173.18       612.88       448.9        363.25       151.96
  206.35       400.91       464.72       521.94       950.52
 1203.4         99.59       525.33      1516.13       826.51
   44.71       829.51       733.58       407.54       770.89
  312.7350159  270.2999878  667.4000244]
**************************************************
Unique values in  product_first_sold_date
['2012-12-02T00:00:00.000000000' '2014-03-03T00:00:00.000000000'
 '1999-07-20T00:00:00.000000000' '1998-12-16T00:00:00.000000000'
 '2015-08-10T00:00:00.000000000' '2006-11-10T00:00:00.000000000'
 '1993-07-15T00:00:00.000000000' '2009-04-12T00:00:00.000000000'
 '1991-08-05T00:00:00.000000000' '2004-08-17T00:00:00.000000000'
 '2011-08-29T00:00:00.000000000' '2015-06-17T00:00:00.000000000'
 '1994-07-12T00:00:00.000000000' '1994-09-09T00:00:00.000000000'
 '2004-07-25T00:00:00.000000000' '2003-09-09T00:00:00.000000000'
 '2004-08-07T00:00:00.000000000' '1992-10-11T00:00:00.000000000'
 '2002-03-22T00:00:00.000000000' '1999-06-23T00:00:00.000000000'
 '2015-05-21T00:00:00.000000000' '2016-02-04T00:00:00.000000000'
 '1993-04-20T00:00:00.000000000' '2012-05-18T00:00:00.000000000'
 '2016-07-09T00:00:00.000000000' '2016-12-06T00:00:00.000000000'
 '2014-10-10T00:00:00.000000000' '2002-10-10T00:00:00.000000000'
 '2016-11-14T00:00:00.000000000' '2006-10-01T00:00:00.000000000'
 '2005-10-22T00:00:00.000000000' '2003-09-10T00:00:00.000000000'
 '1995-10-24T00:00:00.000000000' '1991-11-07T00:00:00.000000000'
 '2005-12-07T00:00:00.000000000' '2003-02-16T00:00:00.000000000'
 '2013-09-16T00:00:00.000000000' '2012-04-10T00:00:00.000000000'
 '2011-01-10T00:00:00.000000000' '2007-12-11T00:00:00.000000000'
 '2005-05-10T00:00:00.000000000' '1997-02-09T00:00:00.000000000'
 '2013-06-09T00:00:00.000000000' '1999-07-26T00:00:00.000000000'
 '2006-02-02T00:00:00.000000000' '2014-07-28T00:00:00.000000000'
 '1993-10-02T00:00:00.000000000' '2016-11-22T00:00:00.000000000'
 '2004-09-28T00:00:00.000000000' '2012-09-15T00:00:00.000000000'
 '2011-05-09T00:00:00.000000000' '1997-10-04T00:00:00.000000000'
 '2015-10-18T00:00:00.000000000' '1991-11-10T00:00:00.000000000'
 '1997-08-25T00:00:00.000000000' '1992-10-02T00:00:00.000000000'
 '2011-05-07T00:00:00.000000000' '2003-01-05T00:00:00.000000000'
 '2004-12-18T00:00:00.000000000' '2010-05-05T00:00:00.000000000'
 '1993-06-23T00:00:00.000000000' '1996-04-05T00:00:00.000000000'
 '2000-05-22T00:00:00.000000000' '1999-12-04T00:00:00.000000000'
 '1993-04-12T00:00:00.000000000' '2011-04-16T00:00:00.000000000'
 '2003-07-21T00:00:00.000000000' '1998-12-17T00:00:00.000000000'
 '2015-04-11T00:00:00.000000000' '1993-05-26T00:00:00.000000000'
 '1995-12-19T00:00:00.000000000' '1991-05-06T00:00:00.000000000'
 '2015-08-02T00:00:00.000000000' '2013-03-12T00:00:00.000000000'
 '1991-07-10T00:00:00.000000000' '2006-05-22T00:00:00.000000000'
 '2000-11-03T00:00:00.000000000' '2002-08-31T00:00:00.000000000'
 '2012-06-04T00:00:00.000000000' '1991-01-21T00:00:00.000000000'
 '1997-05-10T00:00:00.000000000' '2003-08-05T00:00:00.000000000'
 '2003-03-18T00:00:00.000000000' '1996-11-09T00:00:00.000000000'
 '2005-08-09T00:00:00.000000000' '2004-01-16T00:00:00.000000000'
 '2008-03-19T00:00:00.000000000' '2009-03-08T00:00:00.000000000'
 '2010-11-05T00:00:00.000000000' '2010-06-07T00:00:00.000000000'
 '2011-03-16T00:00:00.000000000' '1993-07-20T00:00:00.000000000'
 '2010-08-20T00:00:00.000000000' '2016-03-29T00:00:00.000000000'
 '2007-08-04T00:00:00.000000000' '1997-01-25T00:00:00.000000000'
 '2001-11-25T00:00:00.000000000' '2003-02-07T00:00:00.000000000'
 '2011-08-24T00:00:00.000000000' '1994-08-10T00:00:00.000000000']
**************************************************

In [11]:
#load data into pandas dataframe..
df3 = pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx",sheet_name="CustomerDemographic")
df3.head(5)

,customer_id,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,tenure
0,1,Laraine,Medendorp,F,93,1953-10-12,Executive Secretary,Health,Mass Customer,N,Yes,11.0
1,2,Eli,Bockman,Male,81,1980-12-16,Administrative Officer,Financial Services,Mass Customer,N,Yes,16.0
2,3,Arlin,Dearle,Male,61,1954-01-20,Recruiting Manager,Property,Mass Customer,N,Yes,15.0
3,4,Talbot,NaN,Male,33,1961-10-03,NaN,IT,Mass Customer,N,No,7.0
4,5,Sheila-kathryn,Calton,Female,56,1977-05-13,Senior Editor,NaN,Affluent Customer,N,Yes,8.0

In [9]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3999 entries, 0 to 3998
Data columns (total 12 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   customer_id                          3999 non-null   int64
 1   first_name                           3999 non-null   object
 2   last_name                            3874 non-null   object
 3   gender                               3999 non-null   object
 4   past_3_years_bike_related_purchases  3999 non-null   int64
 5   DOB                                  3912 non-null   datetime64[ns]
 6   job_title                            3493 non-null   object
 7   job_industry_category                3343 non-null   object
 8   wealth_segment                       3999 non-null   object
 9   deceased_indicator                   3999 non-null   object
 10  owns_car                             3999 non-null   object
 11  tenure                               3912 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(2), object(8)
memory usage: 375.0+ KB

In [10]:
#load data into pandas dataframe..
df4 = pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx",sheet_name="CustomerAddress")
df4.head(5)

,customer_id,address,postcode,state,country,property_valuation
0,1,060 Morning Avenue,2016,New South Wales,Australia,10
1,2,6 Meadow Vale Court,2153,New South Wales,Australia,10
2,4,0 Holy Cross Court,4211,QLD,Australia,9
3,5,17979 Del Mar Point,2448,New South Wales,Australia,4
4,6,9 Oakridge Court,3216,VIC,Australia,9

In [ ]:
df4.info()

In [12]:
#load data into pandas dataframe..
df2 = pd.read_excel("KPMG_VI_New_raw_data_update_final.xlsx",sheet_name="NewCustomerList")
df2.head(5)

,first_name,last_name,gender,past_3_years_bike_related_purchases,DOB,job_title,job_industry_category,wealth_segment,deceased_indicator,owns_car,...,state,country,property_valuation,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Rank,Value
0,Chickie,Brister,Male,86,1957-07-12,General Manager,Manufacturing,Mass Customer,N,Yes,...,QLD,Australia,6,1.07,1.3375,1.671875,1.421094,1,1,1.718750
1,Morly,Genery,Male,69,1970-03-22,Structural Engineer,Property,Mass Customer,N,No,...,NSW,Australia,11,0.73,0.7300,0.912500,0.775625,1,1,1.718750
2,Ardelis,Forrester,Female,10,1974-08-28,Senior Cost Accountant,Financial Services,Affluent Customer,N,No,...,VIC,Australia,5,0.42,0.4200,0.420000,0.420000,1,1,1.718750
3,Lucine,Stutt,Female,64,1979-01-28,Account Representative III,Manufacturing,Affluent Customer,N,Yes,...,QLD,Australia,1,0.64,0.8000,0.800000,0.800000,4,4,1.703125
4,Melinda,Hadlee,Female,34,1965-09-21,Financial Analyst,Financial Services,Affluent Customer,N,No,...,NSW,Australia,9,0.53,0.5300,0.662500,0.662500,4,4,1.703125

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 23 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   first_name                           1000 non-null   object
 1   last_name                            971 non-null    object
 2   gender                               1000 non-null   object
 3   past_3_years_bike_related_purchases  1000 non-null   int64
 4   DOB                                  983 non-null    datetime64[ns]
 5   job_title                            894 non-null    object
 6   job_industry_category                835 non-null    object
 7   wealth_segment                       1000 non-null   object
 8   deceased_indicator                   1000 non-null   object
 9   owns_car                             1000 non-null   object
 10  tenure                               1000 non-null   int64
 11  address                              1000 non-null   object
 12  postcode                             1000 non-null   int64
 13  state                                1000 non-null   object
 14  country                              1000 non-null   object
 15  property_valuation                   1000 non-null   int64
 16  Unnamed: 16                          1000 non-null   float64
 17  Unnamed: 17                          1000 non-null   float64
 18  Unnamed: 18                          1000 non-null   float64
 19  Unnamed: 19                          1000 non-null   float64
 20  Unnamed: 20                          1000 non-null   int64
 21  Rank                                 1000 non-null   int64
 22  Value                                1000 non-null   float64
dtypes: datetime64[ns](1), float64(5), int64(6), object(11)
memory usage: 179.8+ KB